import type { Listing } from "@/lib/data";

export const additionalListings = [
  {
    name: "RecoveryHUB",
    additionalCategories: ["sauna"],
    category: "recovery", territory: "island", area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "A recovery studio combining cold plunge, sauna and compression therapy.", "zh-hk": "結合冰浴、桑拿及氣壓恢復療程嘅專門空間。" },
    tags: { en: ["Cold plunge", "Sauna", "Compression"], "zh-hk": ["冰浴", "桑拿", "氣壓恢復"] },
    address: { en: "Flat J, 2/F, Lai Yuen Apartments, 61 Russell Street", "zh-hk": "羅素街61號麗園大廈2樓J室" }, url: "https://www.recoveryhubhk.com/",
  },
  {
    name: "ACME Central",
    category: "recovery", territory: "island", area: { en: "Central", "zh-hk": "中環" },
    description: { en: "Private contrast-therapy suites for alternating heat and cold recovery.", "zh-hk": "提供私人冷熱交替恢復套房，方便按自己節奏進行熱療同冰浴。" },
    tags: { en: ["Contrast therapy", "Private suite"], "zh-hk": ["冷熱交替", "私人套房"] },
    address: { en: "Level 8, Baskerville House, 13 Duddell Street", "zh-hk": "都爹利街13號樂成行8樓" }, url: "https://visit-acme.com/",
  },
  {
    name: "Sauna Rituals at The Hideout",
    additionalCategories: ["recovery"],
    category: "sauna", territory: "new-territories", area: { en: "Mui Wo", "zh-hk": "梅窩" },
    description: { en: "A private members' sauna and ice-bath ritual in a rural Lantau setting.", "zh-hk": "位於大嶼山郊外，提供會員制私人桑拿及冰浴體驗。" },
    tags: { en: ["Sauna", "Ice bath", "Members"], "zh-hk": ["桑拿", "冰浴", "會員制"] },
    url: "https://thesaunarituals.com/",
  },
  {
    name: "The Ice Bath Club — Kennedy Town",
    additionalCategories: ["sauna"],
    category: "recovery", territory: "island", area: { en: "Kennedy Town", "zh-hk": "堅尼地城" },
    description: { en: "A social recovery club with communal cold baths, sauna and hot bath.", "zh-hk": "設有共享冰浴、桑拿同熱水浴嘅社交恢復空間。" },
    tags: { en: ["Ice bath", "Sauna", "Social"], "zh-hk": ["冰浴", "桑拿", "社群"] },
    address: { en: "38 Belcher's Street", "zh-hk": "卑路乍街38號" }, url: "https://www.theicebathclubs.com/hk/hong-kong",
  },
  {
    name: "Coastal Fitness Dream Room",
    additionalCategories: ["sauna", "movement"],
    category: "recovery", territory: "island", area: { en: "North Point", "zh-hk": "北角" },
    description: { en: "A dedicated recovery room with sauna and ice bath inside Coastal Fitness.", "zh-hk": "Coastal Fitness 內設嘅專屬恢復室，備有桑拿及冰浴。" },
    tags: { en: ["Ice bath", "Sauna", "Gym"], "zh-hk": ["冰浴", "桑拿", "健身室"] },
    address: { en: "G/F, Shop 3, Victoria Centre, 15 Watson Road", "zh-hk": "屈臣道15號維多利中心地下3號舖" }, url: "https://www.coastalfitnesshk.com/the-dream-room",
  },
  {
    name: "ONYX Admiralty",
    additionalCategories: ["recovery", "movement"],
    sports: ["gym"],
    category: "sauna", territory: "island", area: { en: "Admiralty", "zh-hk": "金鐘" },
    description: { en: "A 24-hour training club with infrared sauna and cold-plunge recovery facilities.", "zh-hk": "24小時訓練會所，設有紅外線桑拿及冰浴恢復設施。" },
    tags: { en: ["Infrared sauna", "Cold plunge", "24 hours"], "zh-hk": ["紅外線桑拿", "冰浴", "24小時"] },
    address: { en: "Tung Hey Building, 14–20 Queen's Road East", "zh-hk": "皇后大道東14至20號東曦大廈" }, url: "https://www.go24fitness.com/en/look-inside/onyx-admiralty",
  },
  {
    name: "GO24 Fitness — Kennedy Town",
    additionalCategories: ["recovery", "movement"],
    category: "sauna", territory: "island", area: { en: "Kennedy Town", "zh-hk": "堅尼地城" },
    description: { en: "A round-the-clock gym with individual infrared sauna and cold-plunge facilities.", "zh-hk": "全天候健身室，設有獨立紅外線桑拿及冰浴設施。" },
    tags: { en: ["Infrared sauna", "Cold plunge", "Gym"], "zh-hk": ["紅外線桑拿", "冰浴", "健身室"] },
    url: "https://www.go24fitness.com/en/recovery",
  },
  {
    name: "Re:set by PURE — Lee Theatre Plaza",
    category: "recovery", territory: "island", area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "PURE's urban recovery concept for structured hot-and-cold contrast sessions.", "zh-hk": "PURE 旗下都市恢復空間，提供有系統嘅冷熱交替體驗。" },
    tags: { en: ["Contrast therapy", "Cold plunge"], "zh-hk": ["冷熱交替", "冰浴"] },
    address: { en: "Lee Theatre Plaza, 99 Percival Street", "zh-hk": "波斯富街99號利舞臺廣場" }, url: "https://www.pure-360.com.hk/en/contact-us/",
  },
  {
    name: "Re:set by PURE — LKF",
    category: "recovery", territory: "island", area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A central recovery space focused on contrast therapy and post-training reset.", "zh-hk": "中環恢復空間，主打冷熱交替同運動後修復。" },
    tags: { en: ["Contrast therapy", "Central"], "zh-hk": ["冷熱交替", "中環"] },
    address: { en: "14/F, California Tower, 32 D'Aguilar Street", "zh-hk": "德己立街32號加州大廈14樓" }, url: "https://www.pure-360.com.hk/en/contact-us/",
  },
  {
    name: "IKIGAI Central — Infrared Sauna",
    category: "sauna", territory: "island", area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A yoga and wellness studio offering a private infrared-sauna experience.", "zh-hk": "瑜伽及健康生活教室，提供私人紅外線桑拿體驗。" },
    tags: { en: ["Infrared sauna", "Private", "Yoga"], "zh-hk": ["紅外線桑拿", "私人", "瑜伽"] },
    url: "https://www.ikigai.hk/en/studios",
  },

  {
    name: "IKIGAI Central",
    category: "movement", territory: "island", area: { en: "Central", "zh-hk": "中環" },
    description: { en: "Boutique yoga, breathwork and meditation in the heart of Central.", "zh-hk": "位於中環嘅精品瑜伽、呼吸練習及冥想教室。" },
    tags: { en: ["Yoga", "Meditation"], "zh-hk": ["瑜伽", "冥想"] }, url: "https://www.ikigai.hk/en/studios",
  },
  {
    name: "IKIGAI Tsim Sha Tsui",
    category: "movement", territory: "kowloon", area: { en: "Tsim Sha Tsui", "zh-hk": "尖沙咀" },
    description: { en: "Boutique yoga and meditation with heated and non-heated class options.", "zh-hk": "精品瑜伽及冥想教室，提供恆溫同非恆溫課堂。" },
    tags: { en: ["Yoga", "Meditation", "Heated classes"], "zh-hk": ["瑜伽", "冥想", "恆溫課堂"] }, url: "https://www.ikigai.hk/en/studios",
  },
  {
    name: "Attic V Climbing",
    category: "movement", territory: "island", area: { en: "Wong Chuk Hang", "zh-hk": "黃竹坑" },
    description: { en: "An indoor bouldering gym with training walls, coaching and community sessions.", "zh-hk": "室內抱石場，設有訓練牆、教練課程及社群活動。" },
    tags: { en: ["Bouldering", "Coaching"], "zh-hk": ["抱石", "教練課程"] }, url: "https://www.atticv.com.hk/",
  },
  ...([
    ["PURE Yoga — apm", "kowloon", "Kwun Tong", "觀塘", "25/F, Millennium City 5, 418 Kwun Tong Road", "觀塘道418號創紀之城五期25樓", "Yoga"],
    ["PURE Yoga — Asia Standard Tower", "island", "Central", "中環", "2/F, Asia Standard Tower, 59–65 Queen's Road Central", "皇后大道中59至65號泛海大廈2樓", "Yoga"],
    ["PURE Fitness — California Tower", "island", "Central", "中環", "19/F, California Tower, 32 D'Aguilar Street", "德己立街32號加州大廈19樓", "Fitness"],
    ["PURE Fitness — ICBC Tower", "island", "Central", "中環", "3/F, ICBC Tower, 3 Garden Road", "花園道3號中國工商銀行大廈3樓", "Fitness"],
    ["PURE Fitness — ifc mall", "island", "Central", "中環", "3/F, ifc mall, 8 Finance Street", "金融街8號國際金融中心商場3樓", "Fitness"],
    ["PURE — K11 MUSEA", "kowloon", "Tsim Sha Tsui", "尖沙咀", "6/F, K11 MUSEA, 18 Salisbury Road", "梳士巴利道18號K11 MUSEA 6樓", "Yoga & fitness"],
    ["PURE Fitness — Kinwick Centre", "island", "Central", "中環", "3/F, Kinwick Centre, 32 Hollywood Road", "荷李活道32號建業榮基中心3樓", "Fitness"],
    ["PURE Fitness — Langham Place", "kowloon", "Mong Kok", "旺角", "7/F, Langham Place, 8 Argyle Street", "亞皆老街8號朗豪坊7樓", "Fitness"],
    ["PURE Yoga — Langham Place", "kowloon", "Mong Kok", "旺角", "9/F, Langham Place, 8 Argyle Street", "亞皆老街8號朗豪坊9樓", "Yoga"],
    ["PURE Fitness — Lee Theatre Plaza", "island", "Causeway Bay", "銅鑼灣", "15/F, Lee Theatre Plaza, 99 Percival Street", "波斯富街99號利舞臺廣場15樓", "Fitness"],
    ["PURE Yoga — Lincoln House", "island", "Quarry Bay", "鰂魚涌", "4/F, Lincoln House, Taikoo Place, 979 King's Road", "英皇道979號太古坊林肯大廈4樓", "Yoga"],
    ["PURE Fitness — Manulife Place", "kowloon", "Kwun Tong", "觀塘", "1/F–2/F, Manulife Place, 348 Kwun Tong Road", "觀塘道348號宏利廣場1至2樓", "Fitness"],
  ] as const).map(([name, territory, areaEn, areaZh, addressEn, addressZh, activity]): Listing => ({
    name, category: "movement", territory, area: { en: areaEn, "zh-hk": areaZh },
    description: { en: `A PURE ${activity.toLowerCase()} club with coached classes and modern training facilities.`, "zh-hk": `PURE ${activity === "Yoga" ? "瑜伽" : activity === "Fitness" ? "健身" : "瑜伽及健身"}會所，提供教練課堂及現代化訓練設施。` },
    tags: { en: [activity, "Classes"], "zh-hk": [activity === "Yoga" ? "瑜伽" : activity === "Fitness" ? "健身" : "瑜伽及健身", "課堂"] },
    address: { en: addressEn, "zh-hk": addressZh }, url: "https://www.pure-360.com.hk/en/clubs/",
  })),

  {
    name: "TREEHOUSE Causeway Bay",
    category: "food", territory: "island", area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "Whole-food, plant-forward bowls, flatbreads and wraps for a quick meal.", "zh-hk": "提供全天然植物為本碗餐、薄餅及卷物嘅快捷餐廳。" },
    tags: { en: ["Plant-forward", "Quick lunch"], "zh-hk": ["植物為本", "快捷午餐"] },
    address: { en: "7 Sharp Street East", "zh-hk": "霎東街7號" }, url: "https://www.treehouse.eco/",
  },
  {
    name: "TREEHOUSE Tsim Sha Tsui",
    category: "food", territory: "kowloon", area: { en: "Tsim Sha Tsui", "zh-hk": "尖沙咀" },
    description: { en: "Plant-forward comfort food served inside HEATH in Tsim Sha Tsui.", "zh-hk": "位於尖沙咀HEATH，主打植物為本健康舒適料理。" },
    tags: { en: ["Plant-forward", "Vegan options"], "zh-hk": ["植物為本", "純素選擇"] },
    address: { en: "Shop S28, B/F, HEATH, 36–44 Nathan Road", "zh-hk": "彌敦道36至44號HEATH地庫S28號舖" }, url: "https://www.treehouse.eco/",
  },
  {
    name: "SaladStop! — Dorset House",
    category: "food", territory: "island", area: { en: "Quarry Bay", "zh-hk": "鰂魚涌" },
    description: { en: "Made-to-order salads, grain bowls and wraps with customisable ingredients.", "zh-hk": "即叫即製沙律、穀物碗及卷物，可自選配料。" },
    tags: { en: ["Salads", "Customisable", "Quick lunch"], "zh-hk": ["沙律", "自選配料", "快捷午餐"] },
    address: { en: "Shop A, 1/F, Dorset House, Taikoo Place", "zh-hk": "太古坊多盛大廈1樓A舖" }, url: "https://saladstop.com.hk/locations/",
  },
  {
    name: "SaladStop! — Exchange Square",
    category: "food", territory: "island", area: { en: "Central", "zh-hk": "中環" },
    description: { en: "Customisable salads, warm grain bowls and wraps in Central.", "zh-hk": "中環即叫即製沙律、暖穀物碗及卷物，可自由配搭。" },
    tags: { en: ["Salads", "Customisable"], "zh-hk": ["沙律", "自選配料"] },
    address: { en: "Shops 311–312, 3/F, Exchange Square", "zh-hk": "交易廣場3樓311至312號舖" }, url: "https://saladstop.com.hk/locations/",
  },
  {
    name: "VEDA",
    category: "food", territory: "island", area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A vegetarian restaurant serving contemporary Indian-inspired dishes throughout the day.", "zh-hk": "全日供應現代印度風味素食料理嘅餐廳。" },
    tags: { en: ["Vegetarian", "Indian-inspired"], "zh-hk": ["素食", "印度風味"] },
    address: { en: "Ovolo Central, 2 Arbuthnot Road", "zh-hk": "亞畢諾道2號奧華酒店" }, url: "https://www.ovolohotels.com/ovolo/central/veda/",
  },
  {
    name: "MANA! SoHo",
    category: "food", territory: "island", area: { en: "SoHo", "zh-hk": "蘇豪" },
    description: { en: "Fast, plant-based flatbreads, bowls and juices with a low-waste approach.", "zh-hk": "主打植物為本薄餅、碗餐及果汁，並實踐低廢營運。" },
    tags: { en: ["Plant-based", "Low waste"], "zh-hk": ["植物為本", "低廢"] },
    address: { en: "8 Staunton Street", "zh-hk": "士丹頓街8號" }, url: "https://www.mana.hk/locations",
  },

  ...([
    ["Slowood — Kennedy Town", "island", "Kennedy Town", "堅尼地城", "Shops 2–3, G/F, The Hudson, 11 Davis Street", "爹核士街11號浚峯地下2至3號舖"],
    ["Slowood — Central Market", "island", "Central", "中環", "Shops 231–233, 2/F, Central Market", "中環街市2樓231至233號舖"],
    ["Slowood — Hysan Place", "island", "Causeway Bay", "銅鑼灣", "Shops B108–B109, B1, Hysan Place", "希慎廣場B1層B108至B109號舖"],
    ["Slowood — Hong Kong Airport", "new-territories", "Chek Lap Kok", "赤鱲角", "Terminal 1 departures restricted area", "一號客運大樓離港禁區"],
  ] as const).map(([name, territory, areaEn, areaZh, addressEn, addressZh]): Listing => ({
    name, category: "shops", territory, area: { en: areaEn, "zh-hk": areaZh },
    description: { en: "A low-waste lifestyle store for pantry staples, personal care and household essentials.", "zh-hk": "低廢生活選物店，提供食品、個人護理及家居日用品。" },
    tags: { en: ["Low waste", "Groceries", "Refill"], "zh-hk": ["低廢", "食品", "補充裝"] },
    address: { en: addressEn, "zh-hk": addressZh }, url: "https://www.slowood.hk/pages/connect-to-slowood",
  })),
  {
    name: "SpiceBox Organics — Mid-Levels",
    category: "shops", territory: "island", area: { en: "Mid-Levels", "zh-hk": "半山" },
    description: { en: "Organic groceries, pantry staples, supplements and low-waste household essentials.", "zh-hk": "搜羅有機食材、健康食品、營養補充品及低廢生活用品。" },
    tags: { en: ["Organic", "Groceries"], "zh-hk": ["有機", "食品"] },
    address: { en: "137 Caine Road", "zh-hk": "堅道137號" }, url: "https://spiceboxorganics.com/home/",
  },
  {
    name: "Live Zero",
    category: "shops", territory: "island", area: { en: "Sai Ying Pun", "zh-hk": "西營盤" },
    description: { en: "A package-free grocery and lifestyle shop with refillable everyday essentials.", "zh-hk": "裸買食品及生活用品店，提供多款可補充日常必需品。" },
    tags: { en: ["Package-free", "Refill", "Groceries"], "zh-hk": ["裸買", "補充裝", "食品"] },
    address: { en: "Shop 4, 1/F, Cheong King Court, 30 High Street", "zh-hk": "高街30號昌景閣1樓4號舖" }, url: "https://livezero.hk/pages/location",
  },
  {
    name: "FoodCraft",
    category: "shops", territory: "island", area: { en: "Kennedy Town", "zh-hk": "堅尼地城" },
    description: { en: "A natural-food store and workshop with fermented foods, pantry goods and pickup service.", "zh-hk": "天然食品店及工作室，提供發酵食品、乾貨及自取服務。" },
    tags: { en: ["Natural food", "Ferments", "Pickup"], "zh-hk": ["天然食品", "發酵食品", "自取"] },
    address: { en: "Flat A, 16/F, Yiuga Factory Building, 62 Victoria Road", "zh-hk": "域多利道62號耀基工廠大廈16樓A室" }, url: "https://www.foodcraft.hk/pages/contact-us",
  },
  {
    name: "Organic Plus — Caine Road",
    category: "shops", territory: "island", area: { en: "Mid-Levels", "zh-hk": "半山" },
    description: { en: "An organic supermarket for fresh produce, groceries and wellness essentials.", "zh-hk": "有機超級市場，提供新鮮農產品、食品及健康生活用品。" },
    tags: { en: ["Organic", "Fresh produce", "Groceries"], "zh-hk": ["有機", "新鮮農產", "食品"] },
    address: { en: "G/F, 79 Caine Road", "zh-hk": "堅道79號地下" }, url: "https://www.organicplus.com.hk/en/Store/Detail?shopid=655",
  },
] satisfies Listing[];
