import type { Listing } from "@/lib/data";

export const hyroxListings: Listing[] = [
  {
    name: "URSUS Fitness",
    category: "movement",
    territory: "island",
    area: { en: "Sai Ying Pun", "zh-hk": "西營盤" },
    description: {
      en: "An official HYROX Training Club offering dedicated race preparation, functional fitness, hybrid conditioning and small-group coaching.",
      "zh-hk": "HYROX 官方訓練會所，提供賽事備戰、功能性體能、混合式訓練及小組教練課堂。",
    },
    tags: { en: ["HYROX", "Functional fitness", "Small groups"], "zh-hk": ["HYROX", "功能性體能", "小組訓練"] },
    sports: ["hyrox", "gym"],
    address: { en: "G/F, Units 5–6, 64–68 Pok Fu Lam Road", "zh-hk": "薄扶林道64至68號地下5至6號舖" },
    phone: "+852 6468 7489",
    url: "https://www.ursusfitness.com/hyrox-training-club",
    source: "URSUS Fitness official website",
  },
  {
    name: "House of Fitness",
    category: "movement",
    territory: "island",
    area: { en: "Sheung Wan", "zh-hk": "上環" },
    description: {
      en: "A coached group-training studio with dedicated HYROX classes covering stations, running and race-day pacing.",
      "zh-hk": "教練帶領小組訓練，HYROX 專項課堂涵蓋各個訓練站、跑步及比賽配速。",
    },
    tags: { en: ["HYROX", "Strength", "Run club"], "zh-hk": ["HYROX", "力量訓練", "跑步會"] },
    sports: ["hyrox", "gym"],
    address: { en: "18 Possession Street", "zh-hk": "水坑口街18號" },
    openingHours: { en: "Mon–Fri 6:30am–10pm; Sat, Sun & public holidays 9am–5pm", "zh-hk": "星期一至五上午6:30至晚上10:00；星期六、日及公眾假期上午9:00至下午5:00" },
    phone: "+852 6045 2325",
    url: "https://hofhk.com/",
    source: "House of Fitness official website",
  },
  {
    name: "FIT01 Training Club",
    category: "movement",
    territory: "island",
    area: { en: "Central", "zh-hk": "中環" },
    description: {
      en: "An official HYROX partner gym running small-group HYROX training alongside personal and functional-fitness coaching.",
      "zh-hk": "HYROX 官方合作健身室，提供小組 HYROX 訓練、私人教練及功能性體能課堂。",
    },
    tags: { en: ["HYROX", "Partner gym", "Small groups"], "zh-hk": ["HYROX", "官方合作健身室", "小組訓練"] },
    sports: ["hyrox", "gym"],
    address: { en: "13/F, Li Dong Building, 9 Li Yuen Street East", "zh-hk": "利源東街9號利東大廈13樓" },
    openingHours: { en: "HYROX class listed Saturday 4:30–5:45pm; confirm the current schedule", "zh-hk": "HYROX 課堂資料為星期六下午4:30至5:45；請向場地確認最新時間表" },
    phone: "+852 9094 2306",
    url: "https://www.fit-01.com/pages/group-classes",
    source: "FIT01 official website",
  },
  {
    name: "DBDB Training",
    category: "movement",
    territory: "new-territories",
    area: { en: "Discovery Bay", "zh-hk": "愉景灣" },
    description: {
      en: "An official outdoor HYROX Training Club with periodised race preparation, running, sleds, sandbags and group conditioning.",
      "zh-hk": "戶外 HYROX 官方訓練會所，提供周期化賽事備戰、跑步、雪橇、沙包及小組體能訓練。",
    },
    tags: { en: ["HYROX", "Outdoor", "Race preparation"], "zh-hk": ["HYROX", "戶外", "賽事備戰"] },
    sports: ["hyrox", "gym"],
    address: { en: "North Plaza Pitches, Discovery Bay", "zh-hk": "愉景灣北廣場運動場" },
    openingHours: { en: "Sessions run six days a week; see the current schedule", "zh-hk": "每星期設有六日訓練；請查看最新時間表" },
    phone: "+852 6897 2454",
    url: "https://dbdbtraining.com/",
    source: "DBDB Training official website",
  },
];
