import type { Listing } from "@/lib/data";

const checked = "Official studio source checked 29 September 2026";

export const pilatesYogaListings = [
  {
    name: "Anhao Wellness — Mid-Levels",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Mid-Levels", "zh-hk": "半山" },
    description: { en: "A boutique studio for reformer and mat Pilates, barre and small-group movement classes.", "zh-hk": "精品運動教室，提供器械及墊上普拉提、Barre 同小組課堂。" },
    tags: { en: ["Reformer Pilates", "Mat Pilates", "Barre"], "zh-hk": ["器械普拉提", "墊上普拉提", "Barre"] },
    address: { en: "G/F and 1/F, 5 Ladder Street, Mid-Levels Sheung Wan", "zh-hk": "上環半山樓梯街5號地下及1樓" },
    url: "https://anhao-wellness.com/", source: checked,
  },
  {
    name: "Anhao Wellness — Causeway Bay",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "A two-floor studio offering reformer and mat Pilates alongside barre classes.", "zh-hk": "兩層高運動教室，提供器械及墊上普拉提，亦有Barre課堂。" },
    tags: { en: ["Reformer Pilates", "Mat Pilates", "Barre"], "zh-hk": ["器械普拉提", "墊上普拉提", "Barre"] },
    address: { en: "6/F and 19/F, 3 Matheson Street", "zh-hk": "勿地臣街3號6樓及19樓" },
    url: "https://anhao-wellness.com/", source: checked,
  },
  {
    name: "Anhao Wellness — Tsim Sha Tsui",
    category: "movement", territory: "kowloon", sports: ["pilates"],
    area: { en: "Tsim Sha Tsui", "zh-hk": "尖沙咀" },
    description: { en: "A Kowloon studio for reformer and mat Pilates, barre and instructor-led movement.", "zh-hk": "九龍區普拉提教室，提供器械、墊上普拉提、Barre 同導師課堂。" },
    tags: { en: ["Reformer Pilates", "Mat Pilates", "Barre"], "zh-hk": ["器械普拉提", "墊上普拉提", "Barre"] },
    address: { en: "2/F and 3/F, 53 Carnarvon Road", "zh-hk": "加拿分道53號2樓及3樓" },
    url: "https://anhao-wellness.com/", source: checked,
  },
  {
    name: "O:RIN — Central",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A Pilates studio offering reformer group classes and private movement sessions.", "zh-hk": "普拉提教室，提供器械小組課堂及私人動作訓練。" },
    tags: { en: ["Reformer Pilates", "Private classes", "Small groups"], "zh-hk": ["器械普拉提", "私人課堂", "小組課堂"] },
    address: { en: "11/F, Wings Building, 110–116 Queen's Road Central", "zh-hk": "皇后大道中110至116號永恆商業大廈11樓" },
    url: "https://www.orin.com.hk/pilates/", source: checked,
  },
  {
    name: "O:RIN — Quarry Bay",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Quarry Bay", "zh-hk": "鰂魚涌" },
    description: { en: "Reformer group classes plus private Pilates, Gyrotonic education and movement sessions.", "zh-hk": "提供器械普拉提小組班、私人普拉提及Gyrotonic動作訓練。" },
    tags: { en: ["Reformer Pilates", "Gyrotonic", "Private classes"], "zh-hk": ["器械普拉提", "Gyrotonic", "私人課堂"] },
    address: { en: "Units 908 and 1606–07, Westlands Centre, 20 Westlands Road", "zh-hk": "華蘭路20號華蘭中心908及1606至07室" },
    url: "https://www.orin.com.hk/pilates/", source: checked,
  },
  {
    name: "O:RIN — Tsim Sha Tsui",
    category: "movement", territory: "kowloon", sports: ["pilates"],
    area: { en: "Tsim Sha Tsui", "zh-hk": "尖沙咀" },
    description: { en: "A Pilates and movement studio with reformer, private and small-group sessions.", "zh-hk": "提供器械普拉提、私人及小組動作課堂嘅專門教室。" },
    tags: { en: ["Reformer Pilates", "Private classes", "Small groups"], "zh-hk": ["器械普拉提", "私人課堂", "小組課堂"] },
    address: { en: "Unit 2, 4/F, Yue Hwa International Building, 1 Kowloon Park Drive", "zh-hk": "九龍公園徑1號裕華國際大廈4樓2室" },
    url: "https://www.orin.com.hk/pilates/", source: checked,
  },
  {
    name: "FLEX Studio — Central",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A long-running studio for classical Pilates, apparatus work and private instruction.", "zh-hk": "主打古典普拉提、器械訓練及私人指導嘅資深運動教室。" },
    tags: { en: ["Classical Pilates", "Apparatus", "Private classes"], "zh-hk": ["古典普拉提", "器械訓練", "私人課堂"] },
    address: { en: "3/F, Man Cheung Building, 15–17 Wyndham Street", "zh-hk": "雲咸街15至17號文祥大廈3樓" },
    url: "https://flexhk.com/", source: checked,
  },
  {
    name: "FLEX Studio — One Island South",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Wong Chuk Hang", "zh-hk": "黃竹坑" },
    description: { en: "A spacious Southside studio for classical Pilates, equipment work and private training.", "zh-hk": "南區寬敞教室，提供古典普拉提、器械及私人訓練。" },
    tags: { en: ["Classical Pilates", "Apparatus", "Southside"], "zh-hk": ["古典普拉提", "器械訓練", "南區"] },
    address: { en: "Shops 2205 and 2209, One Island South, 2 Heung Yip Road", "zh-hk": "香葉道2號One Island South 2205及2209室" },
    url: "https://flexhk.com/", source: checked,
  },
  {
    name: "Senses Studio — Central",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A Pilates-focused Central studio with reformer group and private class options.", "zh-hk": "中環普拉提專門教室，提供器械小組班及私人課堂。" },
    tags: { en: ["Reformer Pilates", "Private classes", "Central"], "zh-hk": ["器械普拉提", "私人課堂", "中環"] },
    address: { en: "1701, H Queen's, 80 Queen's Road Central", "zh-hk": "皇后大道中80號H Queen's 17樓1701室" },
    url: "https://senses-studio.co/pages/location", source: checked,
  },
  {
    name: "Senses Studio — Causeway Bay",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "A Pilates-only branch with premium reformers, small-group sessions and private classes.", "zh-hk": "普拉提專門分店，設有專業器械，提供小組及私人課堂。" },
    tags: { en: ["Reformer Pilates", "Small groups", "Private classes"], "zh-hk": ["器械普拉提", "小組課堂", "私人課堂"] },
    address: { en: "20/F, The Hedon, 11 Matheson Street", "zh-hk": "勿地臣街11號The Hedon 20樓" },
    url: "https://senses-studio.co/pages/location", source: checked,
  },
  {
    name: "Senses Studio — Quarry Bay",
    category: "movement", territory: "island", sports: ["yoga", "pilates"],
    area: { en: "Quarry Bay", "zh-hk": "鰂魚涌" },
    description: { en: "A light-filled studio for yoga, reformer Pilates and private sessions near Taikoo Place.", "zh-hk": "鄰近太古坊嘅光猛教室，提供瑜伽、器械普拉提及私人課堂。" },
    tags: { en: ["Yoga", "Reformer Pilates", "Private classes"], "zh-hk": ["瑜伽", "器械普拉提", "私人課堂"] },
    address: { en: "1906, 19/F, Westlands Centre, 20 Westlands Road", "zh-hk": "華蘭路20號華蘭中心19樓1906室" },
    url: "https://senses-studio.co/pages/location", source: checked,
  },
  {
    name: "Senses Studio — Lai Chi Kok",
    category: "movement", territory: "kowloon", sports: ["yoga", "pilates"],
    area: { en: "Lai Chi Kok", "zh-hk": "荔枝角" },
    description: { en: "A neighbourhood studio offering yoga and reformer Pilates in small-group formats.", "zh-hk": "社區運動教室，提供瑜伽及器械普拉提小組課堂。" },
    tags: { en: ["Yoga", "Reformer Pilates", "Small groups"], "zh-hk": ["瑜伽", "器械普拉提", "小組課堂"] },
    address: { en: "Unit B, 31/F, Billion Plaza II, 10 Cheung Yue Street", "zh-hk": "長裕街10號億京廣場二期31樓B室" },
    url: "https://senses-studio.co/pages/location", source: checked,
  },
  {
    name: "Senses Studio — Kwun Tong",
    category: "movement", territory: "kowloon", sports: ["yoga", "pilates"],
    area: { en: "Kwun Tong", "zh-hk": "觀塘" },
    description: { en: "Separate yoga and Pilates rooms with group classes and flexible app-based booking.", "zh-hk": "設有獨立瑜伽及普拉提教室，提供小組課堂及手機預約。" },
    tags: { en: ["Yoga", "Reformer Pilates", "Group classes"], "zh-hk": ["瑜伽", "器械普拉提", "小組課堂"] },
    address: { en: "Rooms B, 30/F and E1, 31/F, TG Place, 10 Shing Yip Street", "zh-hk": "成業街10號TG Place 30樓B室及31樓E1室" },
    url: "https://senses-studio.co/pages/location", source: checked,
  },
  {
    name: "Absolute Boutique Fitness — Malahon Centre",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A boutique fitness studio with reformer Pilates and personal Pilates sessions.", "zh-hk": "精品健身教室，提供器械普拉提及私人普拉提課堂。" },
    tags: { en: ["Reformer Pilates", "Personal training", "Boutique"], "zh-hk": ["器械普拉提", "私人訓練", "精品教室"] },
    address: { en: "9/F, Malahon Centre, 10–12 Stanley Street", "zh-hk": "士丹利街10至12號萬利豐中心9樓" },
    url: "https://www.absoluteboutiquefitness.com.hk/", source: checked,
  },
  {
    name: "Absolute Boutique Fitness — On Hing Building",
    category: "movement", territory: "island", sports: ["pilates"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A Central studio combining reformer Pilates with rhythm cycling classes.", "zh-hk": "中環運動教室，結合器械普拉提及節奏單車課堂。" },
    tags: { en: ["Reformer Pilates", "Rhythm cycling", "Classes"], "zh-hk": ["器械普拉提", "節奏單車", "課堂"] },
    address: { en: "Units A–D, 5/F, On Hing Building, 1 On Hing Terrace", "zh-hk": "安慶臺1號安慶大廈5樓A至D室" },
    url: "https://www.absoluteboutiquefitness.com.hk/", source: checked,
  },
  {
    name: "Pilates SENS",
    category: "movement", territory: "new-territories", sports: ["pilates"],
    area: { en: "Shek Mun", "zh-hk": "石門" },
    description: { en: "A Pilates and Gyrotonic studio with private, rehabilitation and pre- or postnatal sessions.", "zh-hk": "提供普拉提、Gyrotonic、復康及產前產後私人課堂嘅教室。" },
    tags: { en: ["Pilates", "Gyrotonic", "Rehabilitation"], "zh-hk": ["普拉提", "Gyrotonic", "復康訓練"] },
    address: { en: "Unit N3, 22/F, W Luxe, 5 On Yiu Street", "zh-hk": "安耀街5號W Luxe 22樓N3室" },
    url: "https://pilatessens.com/", source: checked,
  },
  {
    name: "Yoga Movement Hong Kong",
    category: "movement", territory: "island", sports: ["yoga"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A modern yoga studio with sixteen formats ranging from slow flow to hot and power classes.", "zh-hk": "現代瑜伽教室，十六種課堂由慢流瑜伽到熱瑜伽及力量流瑜伽都有。" },
    tags: { en: ["Yoga", "Hot yoga", "Beginner-friendly"], "zh-hk": ["瑜伽", "熱瑜伽", "初學者友善"] },
    address: { en: "16/F, H Queen's, 80 Queen's Road Central", "zh-hk": "皇后大道中80號H Queen's 16樓" },
    url: "https://yogamovementhk.com/", source: checked,
  },
  {
    name: "Be Earth — Central",
    category: "movement", territory: "island", sports: ["yoga", "pilates"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "A multi-room studio for warm and hot yoga, reformer Pilates, mat Pilates and barre.", "zh-hk": "多房運動教室，提供暖房及熱瑜伽、器械與墊上普拉提及Barre。" },
    tags: { en: ["Hot yoga", "Reformer Pilates", "Barre"], "zh-hk": ["熱瑜伽", "器械普拉提", "Barre"] },
    address: { en: "2/F and 7/F, On Building, 162 Queen's Road Central", "zh-hk": "皇后大道中162號On Building 2樓及7樓" },
    url: "https://www.beearth.com.hk/studio/central", source: checked,
  },
  {
    name: "Anahata Yoga",
    category: "movement", territory: "island", sports: ["yoga"],
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "An established studio with a broad timetable of group yoga, private classes and teacher training.", "zh-hk": "資深瑜伽教室，提供多元小組瑜伽、私人課堂及導師培訓。" },
    tags: { en: ["Yoga", "Private classes", "Teacher training"], "zh-hk": ["瑜伽", "私人課堂", "導師培訓"] },
    address: { en: "20/F, One Lyndhurst Tower, 1 Lyndhurst Terrace", "zh-hk": "擺花街1號One Lyndhurst Tower 20樓" },
    url: "https://www.anahatayoga.com.hk/", source: checked,
  },
  {
    name: "A Yoga Studio HK",
    category: "movement", territory: "island", sports: ["yoga"],
    area: { en: "Wan Chai", "zh-hk": "灣仔" },
    description: { en: "An independent Wan Chai studio for instructor-led yoga classes and regular practice.", "zh-hk": "灣仔獨立瑜伽教室，提供導師帶領課堂及日常練習。" },
    tags: { en: ["Yoga", "Independent studio", "Classes"], "zh-hk": ["瑜伽", "獨立教室", "課堂"] },
    address: { en: "Unit 02, 9/F, Keen Hung Commercial Building, 80 Queen's Road East", "zh-hk": "皇后大道東80號堅雄商業大廈9樓02室" },
    url: "https://www.ayogastudiohk.com/", source: checked,
  },
  {
    name: "ATSUMARU Yoga",
    category: "movement", territory: "kowloon", sports: ["yoga"],
    area: { en: "Cheung Sha Wan", "zh-hk": "長沙灣" },
    description: { en: "A neighbourhood studio offering aerial and mat-based yoga classes throughout the week.", "zh-hk": "社區瑜伽教室，全星期提供空中及墊上瑜伽課堂。" },
    tags: { en: ["Aerial yoga", "Mat yoga", "Classes"], "zh-hk": ["空中瑜伽", "墊上瑜伽", "課堂"] },
    address: { en: "B01, 11/F, NCB Innovation Centre, 888 Lai Chi Kok Road", "zh-hk": "荔枝角道888號NCB Innovation Centre 11樓B01室" },
    url: "https://www.atsumaruyogahk.com/", source: checked,
  },
  {
    name: "Enjoyoga",
    category: "movement", territory: "new-territories", sports: ["yoga", "pilates"],
    area: { en: "Tsuen Wan", "zh-hk": "荃灣" },
    description: { en: "A small-group studio in Tsuen Wan offering yoga and mat Pilates classes.", "zh-hk": "荃灣小組運動教室，提供瑜伽及墊上普拉提課堂。" },
    tags: { en: ["Yoga", "Mat Pilates", "Small groups"], "zh-hk": ["瑜伽", "墊上普拉提", "小組課堂"] },
    address: { en: "Room 8B, 7/F, TCL Tower, 8 Tai Chung Road", "zh-hk": "大涌道8號TCL Tower 7樓8B室" },
    url: "https://www.enjoyoga.online/", source: checked,
  },
  {
    name: "PAUSE Health & Wellness — Mui Wo",
    category: "movement", territory: "new-territories", sports: ["yoga", "pilates"],
    area: { en: "Mui Wo", "zh-hk": "梅窩" },
    description: { en: "A Lantau wellness studio bringing together yoga, Pilates, dance and community classes.", "zh-hk": "大嶼山健康生活教室，集合瑜伽、普拉提、舞蹈及社區課堂。" },
    tags: { en: ["Yoga", "Pilates", "Dance"], "zh-hk": ["瑜伽", "普拉提", "舞蹈"] },
    address: { en: "G/F, 8 Ngan Kwong Wan Road", "zh-hk": "銀礦灣路8號地下" },
    url: "https://www.pause.hk/find-us", source: checked,
  },
  {
    name: "Jesel Studio",
    category: "movement", territory: "island", sports: ["yoga", "pilates"],
    area: { en: "Wan Chai", "zh-hk": "灣仔" },
    description: { en: "A welcoming studio for Pilates, yoga and mind-body wellness classes in Wan Chai.", "zh-hk": "灣仔身心運動教室，提供普拉提、瑜伽及健康生活課堂。" },
    tags: { en: ["Pilates", "Yoga", "Wellness"], "zh-hk": ["普拉提", "瑜伽", "身心健康"] },
    address: { en: "10/F, Shun Pont Commercial Building, 5 Thomson Road", "zh-hk": "譚臣道5號信邦商業大廈10樓" },
    url: "https://www.jeselstudio.com/", source: checked,
  },
] satisfies Listing[];
