import type { Listing } from "./data";

const checked = "Operator source checked 2026-09-07";

export const privateWellness: Listing[] = [
  {
    name: { en: "Thrive Body", "zh-hk": "Thrive Body" },
    category: "movement",
    additionalCategories: ["recovery", "sauna"],
    territory: "island",
    area: { en: "Central", "zh-hk": "中環" },
    description: { en: "Boutique training and wellness studio with personal training, yoga and an open-air sauna and ice bath.", "zh-hk": "精品健身及健康工作室，提供私人訓練、瑜伽，以及戶外桑拿同冰浴。" },
    tags: { en: ["Private facility", "Gym", "Yoga", "Ice bath", "Sauna"], "zh-hk": ["私人設施", "健身", "瑜伽", "冰浴", "桑拿"] },
    sports: ["gym", "yoga"],
    address: { en: "12/A, Ho Lee Commercial Building, 38–44 D’Aguilar Street, Central", "zh-hk": "中環德己立街38至44號好利商業大廈12樓A室" },
    url: "https://www.thrivebody.info/",
    source: checked,
  },
  {
    name: { en: "Ladies Recreation Club", "zh-hk": "婦女遊樂會" }, category: "movement", territory: "island",
    area: { en: "Mid-Levels", "zh-hk": "半山" },
    description: { en: "Private members’ club with ten tennis courts, indoor and outdoor pools, a gym and multi-purpose sports hall.", "zh-hk": "私人會員會所，設有十個網球場、室內外泳池、健身室及多用途體育館。" },
    tags: { en: ["Members only", "Tennis", "Swimming", "Gym"], "zh-hk": ["會員專用", "網球", "游泳", "健身"] }, sports: ["tennis", "swimming", "gym"],
    address: { en: "10 Old Peak Road, Mid-Levels", "zh-hk": "半山舊山頂道10號" }, url: "https://www.lrc.com.hk/", source: checked,
  },
  {
    name: { en: "The Dynasty Club", "zh-hk": "皇朝會" }, category: "movement", additionalCategories: ["sauna"], territory: "island",
    area: { en: "Wan Chai", "zh-hk": "灣仔" },
    description: { en: "Members-only club with gym, tennis, squash, pickleball, pools, sauna and steam room.", "zh-hk": "會員制會所，設有健身室、網球、壁球、匹克球、泳池、桑拿及蒸氣浴。" },
    tags: { en: ["Members only", "Racquet sports", "Swimming", "Sauna"], "zh-hk": ["會員專用", "球拍運動", "游泳", "桑拿"] }, sports: ["gym", "tennis", "squash", "pickleball", "swimming", "badminton", "basketball", "table-tennis"],
    address: { en: "South West Tower, Convention Plaza, 1 Harbour Road, Wan Chai", "zh-hk": "灣仔港灣道1號會展廣場西南座" }, url: "https://www.dynastyclub.com.hk/en/sport-recreations/facilities", source: checked,
  },
  {
    name: { en: "Jewish Community Centre Sports Club", "zh-hk": "猶太社區中心體育會" }, category: "movement", territory: "island",
    area: { en: "Mid-Levels", "zh-hk": "半山" },
    description: { en: "Member facility with indoor tennis, badminton and squash courts, gym, dance studio and heated pool.", "zh-hk": "會員設施，提供室內網球、羽毛球、壁球、健身室、舞蹈室及恆溫泳池。" },
    tags: { en: ["Members only", "Indoor courts", "Swimming"], "zh-hk": ["會員專用", "室內球場", "游泳"] }, sports: ["tennis", "badminton", "squash", "gym", "dance", "swimming"],
    address: { en: "70 Robinson Road, Mid-Levels", "zh-hk": "半山羅便臣道70號" }, url: "https://jcc.org.hk/pages/health-fitness", source: checked,
  },
  {
    name: { en: "The Country Club at Hong Lok Yuen", "zh-hk": "康樂園鄉村俱樂部" }, category: "movement", additionalCategories: ["sauna"], territory: "new-territories",
    area: { en: "Hong Lok Yuen", "zh-hk": "康樂園" },
    description: { en: "Private club with pools, gym, tennis, squash, pickleball, court sports, saunas and Jacuzzis.", "zh-hk": "私人會所，設有泳池、健身室、網球、壁球、匹克球、球場、桑拿及按摩池。" },
    tags: { en: ["Members only", "Multi-sport", "Sauna"], "zh-hk": ["會員專用", "多項運動", "桑拿"] }, sports: ["swimming", "gym", "yoga", "tennis", "squash", "table-tennis", "badminton", "basketball", "pickleball"],
    address: { en: "8 Town Centre Crescent, Hong Lok Yuen", "zh-hk": "康樂園市中心徑8號" }, url: "https://www.cchly.com/", source: checked,
  },
  {
    name: { en: "United Services Recreation Club", "zh-hk": "三軍會" }, category: "movement", territory: "kowloon",
    area: { en: "King’s Park", "zh-hk": "京士柏" },
    description: { en: "Private club with four tennis courts, squash, multi-sport court, pool, fitness centre and Pilates studio.", "zh-hk": "私人會所，設有四個網球場、壁球、多用途球場、泳池、健身室及普拉提教室。" },
    tags: { en: ["Members only", "Tennis", "Swimming", "Fitness"], "zh-hk": ["會員專用", "網球", "游泳", "健身"] }, sports: ["tennis", "squash", "swimming", "gym", "yoga", "basketball"],
    address: { en: "1 Gascoigne Road, King’s Park", "zh-hk": "京士柏加士居道1號" }, url: "https://www.usrc.org.hk/our-facilities.html", source: checked,
  },
  {
    name: { en: "Hong Kong Football Club", "zh-hk": "香港足球會" }, category: "movement", additionalCategories: ["sauna"], territory: "island",
    area: { en: "Happy Valley", "zh-hk": "跑馬地" },
    description: { en: "Members’ sports club with football, rugby, hockey, racquet sports, gym, pool, sauna and steam rooms.", "zh-hk": "會員體育會，提供足球、欖球、曲棍球、球拍運動、健身、泳池、桑拿及蒸氣浴。" },
    tags: { en: ["Members only", "Football", "Racquet sports", "Sauna"], "zh-hk": ["會員專用", "足球", "球拍運動", "桑拿"] }, sports: ["football", "tennis", "squash", "badminton", "basketball", "swimming", "gym"],
    address: { en: "3 Sports Road, Happy Valley", "zh-hk": "跑馬地體育道3號" }, url: "https://www.hkfc.com/facilities/", source: checked,
  },
  {
    name: { en: "Discovery Bay Recreation Club", "zh-hk": "愉景灣康樂會" }, category: "movement", additionalCategories: ["sauna"], territory: "new-territories",
    area: { en: "Discovery Bay", "zh-hk": "愉景灣" },
    description: { en: "Private club with pools, eleven tennis courts, pickleball, padel, squash, gym, sauna and steam rooms.", "zh-hk": "私人會所，設有泳池、十一個網球場、匹克球、板式網球、壁球、健身室、桑拿及蒸氣浴。" },
    tags: { en: ["Members only", "Racquet sports", "Sauna"], "zh-hk": ["會員專用", "球拍運動", "桑拿"] }, sports: ["swimming", "tennis", "pickleball", "padel", "squash", "table-tennis", "gym", "dance"],
    address: { en: "Discovery Bay, Lantau Island", "zh-hk": "大嶼山愉景灣" }, url: "https://www.dbrc.hk/en/sport.html?club=1&id=1438407458&type=1", source: checked,
  },
  {
    name: { en: "Police Officers’ Club", "zh-hk": "警官會所" }, category: "movement", territory: "island",
    area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "Restricted members’ club with pool, tennis, indoor court sports, squash, fitness centre and golf simulator.", "zh-hk": "限定會員會所，設有泳池、網球、室內球類、壁球、健身室及高爾夫模擬器。" },
    tags: { en: ["Restricted access", "Multi-sport", "Swimming"], "zh-hk": ["限制使用", "多項運動", "游泳"] }, sports: ["swimming", "tennis", "badminton", "basketball", "volleyball", "table-tennis", "squash", "gym"],
    address: { en: "28 Hung Hing Road, Causeway Bay", "zh-hk": "銅鑼灣鴻興道28號" }, url: "https://poc-psrc.com.hk/Card/AboutUs", source: checked,
  },
  {
    name: { en: "Police Sports and Recreation Club", "zh-hk": "警察體育遊樂會" }, category: "movement", additionalCategories: ["sauna"], territory: "kowloon",
    area: { en: "Prince Edward", "zh-hk": "太子" },
    description: { en: "Restricted members’ club with a 50-metre pool, pitches, courts, gym, bowling, sauna and steam bath.", "zh-hk": "限定會員會所，設有50米泳池、球場、健身室、保齡球、桑拿及蒸氣浴。" },
    tags: { en: ["Restricted access", "Multi-sport", "Sauna"], "zh-hk": ["限制使用", "多項運動", "桑拿"] }, sports: ["swimming", "football", "tennis", "badminton", "basketball", "volleyball", "squash", "table-tennis", "gym"],
    address: { en: "430 Sai Yeung Choi Street North, Prince Edward", "zh-hk": "太子西洋菜北街430號" }, url: "https://poc-psrc.com.hk/Card/AboutUs", source: checked,
  },
  ...[
    ["YEARS — Sham Shui Po", "素年 — 深水埗", "Sham Shui Po", "深水埗", "kowloon", "191–199 Fuk Wah Street, Sham Shui Po", "深水埗福華街191至199號"],
    ["BE WITH YEARS — Whampoa", "素年 — 黃埔", "Whampoa", "黃埔", "kowloon", "Shop G27, Pebbles World, Whampoa Garden, Hung Hom", "紅磡黃埔天地百寶坊地下G27號舖"],
    ["HERE WITH YEARS — Tai Koo Shing", "素年 — 太古城", "Tai Koo Shing", "太古城", "island", "Shop G517, Ko On Mansion, 9 Tai Yu Avenue, Tai Koo Shing", "太古城太裕路9號高安閣G517號舖"],
    ["PLAY WITH YEARS — West Kowloon", "素年 — 西九文化區", "West Kowloon", "西九龍", "kowloon", "Shop GF-05, Art Park, West Kowloon Cultural District", "西九文化區藝術公園地下GF-05號舖"],
    ["BEAR BY YEARS — Lai Chi Kok", "啤啤熊 — 荔枝角", "Lai Chi Kok", "荔枝角", "kowloon", "Shop 2, G/F, Billion Plaza 2, Cheung Yue Street, Lai Chi Kok", "荔枝角長裕街億京廣場二期地下2號舖"],
    ["WANAKA — Blue House", "WANAKA — 藍屋", "Wan Chai", "灣仔", "island", "8 King Sing Street, Blue House, Wan Chai", "灣仔藍屋景星街8號"],
  ].map(([en, zh, areaEn, areaZh, territory, addressEn, addressZh]) => ({
    name: { en, "zh-hk": zh }, category: "food" as const, territory: territory as Listing["territory"],
    area: { en: areaEn, "zh-hk": areaZh },
    description: { en: "Plant-based neighbourhood restaurant from the YEARS family, with current menus and hours published by the operator.", "zh-hk": "YEARS旗下植物為本社區餐廳，官方有公布最新餐單及營業時間。" },
    tags: { en: ["Plant-based", "Vegan options"], "zh-hk": ["植物為本", "純素選擇"] },
    address: { en: addressEn, "zh-hk": addressZh }, url: "https://www.yearshk.com/pages/menu", source: checked,
  })),
  {
    name: { en: "Green Concepts Health Shop", "zh-hk": "Green Concepts 健康店" }, category: "shops", territory: "island",
    area: { en: "Causeway Bay", "zh-hk": "銅鑼灣" },
    description: { en: "Walk-in health shop for natural foods, supplements, personal care, filters and health books.", "zh-hk": "實體健康店，售賣天然食品、營養補充品、個人護理用品、濾水產品及健康書籍。" },
    tags: { en: ["Natural foods", "Supplements", "Walk-in"], "zh-hk": ["天然食品", "營養補充品", "實體店"] },
    address: { en: "2/F, Prosperous Commercial Building, 54–58 Jardine’s Bazaar, Causeway Bay", "zh-hk": "銅鑼灣渣甸街54至58號富盛商業大廈2樓" }, url: "https://online.healthshop.com.hk/default/place-order", source: checked,
  },
  ...[
    ["Health Aims — Ma On Shan", "Health Aims — 馬鞍山", "Ma On Shan", "馬鞍山", "Shop 2118, Level 2, Ma On Shan Plaza", "馬鞍山廣場2樓2118號舖"],
    ["Health Aims — Tai Po", "Health Aims — 大埔", "Tai Po", "大埔", "Shop 051B, 2/F, Zone A, Tai Po Mega Mall, 9 On Pong Road", "大埔安邦路9號大埔超級城A區2樓051B號舖"],
    ["Health Aims — Tuen Mun", "Health Aims — 屯門", "Tuen Mun", "屯門", "Shop R116, Level 1, Butterfly Plaza, 1 Wu Chui Road", "屯門湖翠路1號蝴蝶廣場1樓R116號舖"],
    ["Health Aims — Tin Shui Wai", "Health Aims — 天水圍", "Tin Shui Wai", "天水圍", "Shop N209A, 2/F, T Town North, Tin Yuet Estate", "天水圍天悅邨T Town North 2樓N209A號舖"],
  ].map(([en, zh, areaEn, areaZh, addressEn, addressZh]) => ({
    name: { en, "zh-hk": zh }, category: "shops" as const, territory: "new-territories" as const,
    area: { en: areaEn, "zh-hk": areaZh }, description: { en: "Physical specialist shop for organic functional products and health-focused essentials.", "zh-hk": "實體專門店，主打有機功能產品及健康生活用品。" },
    tags: { en: ["Organic products", "Physical shop"], "zh-hk": ["有機產品", "實體店"] }, address: { en: addressEn, "zh-hk": addressZh }, url: "https://www.healthygiant.hk/en/pages/store-locations", source: checked,
  })),
  ...[
    ["Solutions Health Care — Causeway Bay", "Solutions Health Care — 銅鑼灣", "Causeway Bay", "銅鑼灣", "island", "Rooms 1104–05, 11/F, Capitol Centre, 5–19 Jardine’s Bazaar", "銅鑼灣渣甸街5至19號京華中心11樓1104至05室"],
    ["Solutions Health Care — Happy Valley", "Solutions Health Care — 跑馬地", "Happy Valley", "跑馬地", "island", "Shop C, G/F, 1A Shan Kwong Road, Happy Valley", "跑馬地山光道1A號地下C舖"],
    ["Solutions Health Care — Mong Kok", "Solutions Health Care — 旺角", "Mong Kok", "旺角", "kowloon", "1/F, 168 Fa Yuen Street, Mong Kok", "旺角花園街168號1樓"],
    ["Solutions Health Care — Cheung Sha Wan", "Solutions Health Care — 長沙灣", "Cheung Sha Wan", "長沙灣", "kowloon", "Room 2806, 28/F, Global Gateway Tower, 63 Wing Hong Street", "長沙灣永康街63號Global Gateway Tower 28樓2806室"],
    ["Solutions Health Care — Yuen Long", "Solutions Health Care — 元朗", "Yuen Long", "元朗", "new-territories", "Shop 3, G/F, 19 Castle Peak Road, Yuen Long", "元朗青山公路19號地下3號舖"],
    ["Solutions Health Care — Sha Tin", "Solutions Health Care — 沙田", "Sha Tin", "沙田", "new-territories", "Unit 2102, 21/F, Tower 1, Grand Central Plaza, 138 Sha Tin Rural Committee Road", "沙田鄉事會路138號新城市中央廣場第1座21樓2102室"],
  ].map(([en, zh, areaEn, areaZh, territory, addressEn, addressZh]) => ({
    name: { en, "zh-hk": zh }, category: "shops" as const, territory: territory as Listing["territory"],
    area: { en: areaEn, "zh-hk": areaZh }, description: { en: "Physical health-care products and services branch listed by the operator.", "zh-hk": "由營運方列出嘅實體健康產品及服務分店。" },
    tags: { en: ["Health products", "Physical branch"], "zh-hk": ["健康產品", "實體分店"] }, address: { en: addressEn, "zh-hk": addressZh }, url: "https://www.healthygiant.hk/en/pages/store-locations", source: checked,
  })),
  {
    name: { en: "Energy Source — Wan Chai", "zh-hk": "Energy Source — 灣仔" }, category: "shops", territory: "island",
    area: { en: "Wan Chai", "zh-hk": "灣仔" }, description: { en: "Physical health-products outlet listed by Healthy Giant’s current store directory.", "zh-hk": "Healthy Giant現行分店目錄列出嘅實體健康產品店。" },
    tags: { en: ["Health products", "Physical branch"], "zh-hk": ["健康產品", "實體分店"] },
    address: { en: "5/F, The Phoenix, 23 Luard Road, Wan Chai", "zh-hk": "灣仔盧押道23號The Phoenix 5樓" }, url: "https://www.healthygiant.hk/en/pages/store-locations", source: checked,
  },
];
