import type { Listing } from "./data";

// Newly opened or newly verified venues checked against official sources on 21 September 2026.
export const venueUpdatesSeptember2026: Listing[] = [
  {
    name: "The Clubhouse Recharge Suite",
    category: "recovery",
    additionalCategories: ["sauna"],
    territory: "island",
    area: { en: "Central", "zh-hk": "中環" },
    description: {
      en: "A private recovery suite pairing a traditional sauna with two cold-plunge barrels in Central.",
      "zh-hk": "位於中環嘅私人恢復空間，設有傳統桑拿及兩個冰浴桶。",
    },
    tags: { en: ["Cold plunge", "Traditional sauna", "Private suite"], "zh-hk": ["冰浴", "傳統桑拿", "私人空間"] },
    url: "https://www.theclubhousehongkong.com/recharge",
    address: { en: "8/F, On Hing Building, 1 On Hing Terrace, Central", "zh-hk": "中環安慶臺1號安慶大廈8樓" },
    source: "Official venue website checked 21 September 2026",
  },
  {
    name: "Pickle Go HK",
    category: "movement",
    territory: "new-territories",
    area: { en: "Shek Mun", "zh-hk": "石門" },
    description: {
      en: "An indoor pickleball venue offering court hire, coaching and social play in Shek Mun.",
      "zh-hk": "位於石門嘅室內匹克球場，提供球場租用、教練課堂及社交球局。",
    },
    tags: { en: ["Pickleball", "Indoor", "Coaching"], "zh-hk": ["匹克球", "室內", "教練課堂"] },
    sports: ["pickleball"],
    url: "https://www.pickle-go.hk/service/",
    address: { en: "Room 2522, Enterprise Centre, 11 On Lai Street, Shek Mun, Sha Tin", "zh-hk": "沙田石門安麗街11號企業中心2522室" },
    source: "Official venue website checked 21 September 2026",
  },
  {
    name: "The Pickleball Lab — Tuen Mun Town Plaza",
    category: "movement",
    territory: "new-territories",
    area: { en: "Tuen Mun", "zh-hk": "屯門" },
    description: {
      en: "Six pickleball courts plus badminton and basketball courts at the mall's tmtp commons sports hub.",
      "zh-hk": "位於商場 tmtp commons 運動空間，設有六個匹克球場，另有羽毛球及籃球場。",
    },
    tags: { en: ["Pickleball", "Badminton", "Basketball"], "zh-hk": ["匹克球", "羽毛球", "籃球"] },
    sports: ["pickleball", "badminton", "basketball"],
    url: "https://www.tmtp.com.hk/en/TMTPCommons",
    address: { en: "4/F, tmtplaza Phase 1, 1 Tuen Shun Street, Tuen Mun", "zh-hk": "屯門屯順街1號屯門市廣場一期4樓" },
    source: "Official tmtplaza website checked 21 September 2026",
  },
  {
    name: "Waterfall Olympic Club — Pickleball",
    category: "movement",
    territory: "kowloon",
    area: { en: "Olympic", "zh-hk": "奧運" },
    description: {
      en: "Outdoor rooftop pickleball at Waterfall Olympic Club, with court bookings available to non-members.",
      "zh-hk": "Waterfall Olympic Club 天台戶外匹克球場，非會員亦可預約。",
    },
    tags: { en: ["Pickleball", "Outdoor", "Non-member booking"], "zh-hk": ["匹克球", "戶外", "非會員可預約"] },
    sports: ["pickleball"],
    url: "https://waterfall.com.hk/pickleball/",
    address: { en: "2/F, Olympian City One, 11 Hoi Fai Road, Kowloon", "zh-hk": "九龍海輝道11號奧海城一期2樓" },
    source: "Official venue website checked 21 September 2026",
  },
  {
    name: "Waterfall Exquisite Wellness — Tsim Sha Tsui",
    category: "sauna",
    additionalCategories: ["movement"],
    territory: "kowloon",
    area: { en: "Tsim Sha Tsui", "zh-hk": "尖沙咀" },
    description: {
      en: "A 24-hour gym with a swimming pool and sauna facilities overlooking Victoria Harbour.",
      "zh-hk": "設有24小時健身室、泳池及桑拿設施，坐擁維港景觀。",
    },
    tags: { en: ["Sauna", "24-hour gym", "Swimming"], "zh-hk": ["桑拿", "24小時健身室", "游泳"] },
    sports: ["gym", "swimming"],
    url: "https://waterfall.com.hk/pickleball/",
    address: { en: "18/F, 20 Nathan Road, Tsim Sha Tsui", "zh-hk": "尖沙咀彌敦道20號18樓" },
    source: "Official venue website checked 21 September 2026",
  },
  {
    name: "Hu Fa Kuang Sports Centre",
    category: "movement",
    territory: "kowloon",
    area: { en: "Kowloon Tong", "zh-hk": "九龍塘" },
    description: {
      en: "CityUHK's new multi-sport centre with 14 badminton or pickleball courts, a gym, squash courts and an indoor track. Access is limited to eligible users and their guests.",
      "zh-hk": "香港城市大學新落成多用途運動中心，設14個羽毛球或匹克球場、健身室、壁球場及室內跑道；只限合資格使用者及其訪客。",
    },
    tags: { en: ["Badminton", "Pickleball", "University access"], "zh-hk": ["羽毛球", "匹克球", "大學使用資格"] },
    sports: ["badminton", "pickleball", "basketball", "volleyball", "squash", "table-tennis", "gym"],
    url: "https://www.cityu.edu.hk/sds/physical-education-wellness-and-sports/sports-and-recreation-facilities/general-information",
    address: { en: "Jockey Club One Health Tower, CityUHK, 83 Tat Chee Avenue, Kowloon Tong", "zh-hk": "九龍塘達之路83號香港城市大學賽馬會健康一體化大樓" },
    source: "Official CityUHK website checked 21 September 2026",
  },
  {
    name: "Dink City",
    category: "movement",
    territory: "island",
    area: { en: "Quarry Bay", "zh-hk": "鰂魚涌" },
    description: {
      en: "An 18,000-square-foot indoor pickleball club with five courts, high ceilings, AI replay and a café lounge.",
      "zh-hk": "佔地18,000平方呎嘅室內匹克球會，設五個球場、高樓底、AI重播及咖啡休息區。",
    },
    tags: { en: ["Pickleball", "Indoor", "AI replay"], "zh-hk": ["匹克球", "室內", "AI重播"] },
    sports: ["pickleball"],
    url: "https://www.dinkhk.com/en/index.php",
    address: { en: "4/F, Kodak House 1, 321 Java Road, Quarry Bay", "zh-hk": "鰂魚涌渣華道321號柯達大廈一期4樓" },
    source: "Official venue website checked 21 September 2026",
  },
];
